[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
openmls = "0.7.1"
openmls_rust_crypto = "0.4.1"
openmls_basic_credential = "0.4.1"
tls_codec = "0.4"
ciborium = "0.2"
hex = "0.4"
anyhow = "1.0"
rand = "0.8"
chrono = "0.4.42"
